# Generated by Django 5.2.8 on 2025-11-07 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('transcript', 'Transcript'), ('audio', 'Audio')], max_length=16)),
                ('summary_label', models.CharField(max_length=16)),
                ('summary_confidence', models.FloatField(default=0.0)),
                ('distribution', models.JSONField(blank=True, default=dict)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('transcript_preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
